モジュールインストールの自動化とdocker-composeによるコンテナ化
JinkaiINT2020/web-PEanalysis pull request #6
Opened 2020-09-24 07:20 UTC by hanzawa99

pythonモジュールと必要なソフトウェアのインストールの自動化スクリプトとDockerfileとymlファイルを追加しました。requirements.txtの一部に変更があります。

2020-09-24 16:15 UTC, who3411 requested changes

2020-09-24 16:15 UTC, who3411 commented on Dockerfile
> +WORKDIR /home
PEiDを動かす際、ホームディレクトリからPEiDを動かすのに必要なファイルを探すようです。今回のDockerfileの場合だと`/root`がホームディレクトリになるので、`WORKDIR /root`としてください。

2020-09-24 16:15 UTC, who3411 commented on Dockerfile
> +WORKDIR /home/web-PEanalysis
こちらも上のコメントと同様、`WORKDIR /root/web-PEanalysis`としてください。

2020-09-24 16:15 UTC, who3411 commented on Dockerfile
> +# PEiDセットアップ
PEiDはREADME.mdに書いてあるようにlibcrypto.so.1.0.0を使用しますが、centOS7には存在しません。この問題に対しては、README.mdのようにcentOS7にある/lib64/libcrypto.so.1.0.2kをシンボリックリンクしておくことで解決できます。なので、PEiDのセットアップのどこかに `RUN ln -s /lib64/libcrypto.so.1.0.2k /lib64/libcrypto.so.1.0.0` を入れておいてください。

2020-09-24 16:15 UTC, who3411 commented on docker-compose.yml
> +            - 8181:5000
portsは、README.mdの`http://localhost:5000`と合わせるため、5000:5000としてください。

2020-09-24 16:25 UTC, who3411 requested changes

2020-09-24 16:25 UTC, who3411 commented on docker-compose.yml
> +    mongo:
https://hub.docker.com/_/mongo/ の Caveatsにあるように、Dockerのmongodbはデータの永続化を行うために、特定の場所にデータを共有する必要があります。今のままだとコンテナを一度再起動するたびにこれまでmongodbに蓄積したデータは全て消えてしまいます。対策として、例えば以下のようにvolumeを用いる方法があります。

```
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./mongo/db:/data/db
            - ./mongo/configdb:/data/config
```

2020-09-24 16:25 UTC, who3411 commented on docker-compose.yml
> +        volumes:
volumesにはpefilesも書いておいてください。
また、uploadsもですが、Dockerfileとの兼ね合いで`/home`ではなく`/root`にしてください。

2020-09-24 16:28 UTC, who3411 commented
最後に、詳しく動作確認せずにファイルなどを共有した私にも問題があるのですが、コンテナ化の際にはweb-PEanalysis本体のコードを一部書き換えないといけませんでした。大変申し訳ありませんが、app.pyの15〜17行目の部分を以下のように書き換えてください。

```
host   = os.getenv('HOST_MONGODB', app.config['HOST_DB'])
port   = os.getenv('PORT_MONGODB', app.config['PORT_DB'])
client = MongoClient(host, port)
db = client[os.getenv('DB_MONGODB', app.config['USE_DB'])]
collection = db[os.getenv('COLLECTION_MONGODB', app.config['USE_COLLECTION'])]
```

2020-09-24 19:04 UTC, hanzawa99 commented on docker-compose.yml
> +        volumes:
ここだけ少しわからないことがあるのですが、volumes に追記するpefiilesはホストのどことappコンテナのどこを指定すればよいですか？

2020-09-24 19:24 UTC, who3411 commented on docker-compose.yml
> +        volumes:
`- ./pefiles:/root/web-PEanalysis/pefiles`ですね。web-PEanalysis動作後にできるpefilesディレクトリを永続化させるためのものです。

2020-09-25 00:04 UTC, who3411 requested changes

2020-09-25 00:04 UTC, who3411 commented on setuptool.py
> +#PEiD
reviewが前後してしまい申し訳ありません。
こちらにも、PEiDのセットアップのどこかに`ln -s /lib64/libcrypto.so.1.0.2k /lib64/libcrypto.so.1.0.0`を入れておいてください。

2020-09-25 02:54 UTC, who3411 approved these changes
私側のレビューは大丈夫です。
あとは担当分野の方にご確認いただいて許可をもらえればマージしてもらって構いません。

2020-09-25 03:40 UTC, merged